# Generated by Django 3.1.7 on 2021-03-09 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('phasechoices', models.CharField(choices=[('DRF', 'Draft'), ('SUB', 'Submitted'), ('PUB', 'Published'), ('ARC', 'Archived'), ('REJ', 'Rejected')], default='DRF', max_length=3, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
