# Generated by Django 3.1.7 on 2021-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.CharField(choices=[('Community', 'Community'), ('Inspiring', 'Inspiring'), ('Sports', 'Sports'), ('Local', 'Local'), ('International', 'International'), ('Undecided', 'Undecided')], default='Undecided', max_length=13),
        ),
        migrations.AlterField(
            model_name='article',
            name='phasechoices',
            field=models.CharField(choices=[('DRF', 'Draft'), ('SUB', 'Submitted'), ('PUB', 'Published'), ('ARC', 'Archived')], default='DRF', max_length=9, null=True),
        ),
    ]
